#!/bin/bash -e
#
# Run analytics on the first day of next month.
# (Even if it fails, at least the snapshot should be ready.)
#

# Wait until the first of the month (UTC).
while [[ $(date -u +%-d) -ne 1 ]]; do
    echo "Date is "$(date -u +%Y-%m-%d)", too soon for analytics."
    sleep 1h
done

date -u -R
(
    echo "Suspending map tiles build"
    WID=$(oozie jobs -oozie http://c5oozie.gbif.org:11000/oozie/ -jobtype coordinator -filter name=MapBuild-Tiles | awk 'NR==3 {print $1}')
    if [ -n "$WID" ]; then
	oozie job -oozie http://c5oozie.gbif.org:11000/oozie/ -suspend $WID
    fi
) || echo "Failed to suspend map tiles build" | mail -s "Failed to suspend map tiles build." mblissett@gbif.org

echo "Starting analytics!"

cd /home/hdfs/analytics/hive/import/hdfs
echo "Creating snapshot"
./create_new_snapshot.sh snapshot $(date -u +%Y%m%d) prod_h occurrence_pipelines_hdfs
echo "Snapshot completed"

sleep 1m

echo "Snapshot $(date +%Y%m%d) (probably) is ready for backup." | mail -s "Quarterly snapshot ready for backup" mblissett@gbif.org

cd /home/hdfs/analytics
echo "Running analytics"
./build.sh -runHbase -runHive -runHadoop -runPrepare -runFigures || echo "Analytics exited with a failure code: $?"
echo "Analytics completed"

echo "Analytics script exited." | mail -s "Analytics script exited -- map tiles needs resuming." mblissett@gbif.org
