#!/bin/bash

TRINO_SERVER=$1
export TRINO_PASSWORD=$2

SNAPSHOT_DB=$3
SNAPSHOT_NAME=$4
SOURCE_DB=$5
SOURCE_TABLE=$6

query="CREATE TABLE $SNAPSHOT_DB.raw_$SNAPSHOT_NAME
WITH (format = 'ORC')
AS
SELECT gbifid AS id, datasetkey AS dataset_id, publishingorgkey AS publisher_id, publishingcountry AS publisher_country
,v_accessrights
,v_bibliographiccitation
,v_language
,v_license
,v_modified
,v_publisher
,v_references
,v_rightsholder
,v_type
,v_institutionid
,v_collectionid
,v_datasetid
,v_institutioncode
,v_collectioncode
,v_datasetname
,v_ownerinstitutioncode
,v_basisofrecord
,v_informationwithheld
,v_datageneralizations
,v_dynamicproperties
,v_occurrenceid
,v_catalognumber
,v_recordnumber
,v_recordedby
,v_recordedbyid
,v_individualcount
,v_organismquantity
,v_organismquantitytype
,v_sex
,v_lifestage
,v_reproductivecondition
,v_behavior
,v_establishmentmeans
,v_degreeofestablishment
,v_pathway
,v_georeferenceverificationstatus
,v_occurrencestatus
,v_preparations
,v_disposition
,v_associatedmedia
,v_associatedoccurrences
,v_associatedreferences
,v_associatedsequences
,v_associatedtaxa
,v_othercatalognumbers
,v_occurrenceremarks
,v_organismid
,v_organismname
,v_organismscope
,v_associatedorganisms
,v_previousidentifications
,v_organismremarks
,v_materialsampleid
,v_eventid
,v_parenteventid
,v_fieldnumber
,v_eventdate
,v_eventtime
,v_startdayofyear
,v_enddayofyear
,v_year
,v_month
,v_day
,v_verbatimeventdate
,v_habitat
,v_samplingprotocol
,v_samplesizevalue
,v_samplesizeunit
,v_samplingeffort
,v_fieldnotes
,v_eventremarks
,v_locationid
,v_highergeographyid
,v_highergeography
,v_continent
,v_waterbody
,v_islandgroup
,v_island
,v_country
,v_countrycode
,v_stateprovince
,v_county
,v_municipality
,v_locality
,v_verbatimlocality
,v_minimumelevationinmeters
,v_maximumelevationinmeters
,v_verbatimelevation
,v_verticaldatum
,v_minimumdepthinmeters
,v_maximumdepthinmeters
,v_verbatimdepth
,v_minimumdistanceabovesurfaceinmeters
,v_maximumdistanceabovesurfaceinmeters
,v_locationaccordingto
,v_locationremarks
,v_decimallatitude
,v_decimallongitude
,v_geodeticdatum
,v_coordinateuncertaintyinmeters
,v_coordinateprecision
,v_pointradiusspatialfit
,v_verbatimcoordinates
,v_verbatimlatitude
,v_verbatimlongitude
,v_verbatimcoordinatesystem
,v_verbatimsrs
,v_footprintwkt
,v_footprintsrs
,v_footprintspatialfit
,v_georeferencedby
,v_georeferenceddate
,v_georeferenceprotocol
,v_georeferencesources
,v_georeferenceremarks
,v_geologicalcontextid
,v_earliesteonorlowesteonothem
,v_latesteonorhighesteonothem
,v_earliesteraorlowesterathem
,v_latesteraorhighesterathem
,v_earliestperiodorlowestsystem
,v_latestperiodorhighestsystem
,v_earliestepochorlowestseries
,v_latestepochorhighestseries
,v_earliestageorloweststage
,v_latestageorhigheststage
,v_lowestbiostratigraphiczone
,v_highestbiostratigraphiczone
,v_lithostratigraphicterms
,v_group
,v_formation
,v_member
,v_bed
,v_identificationid
,v_verbatimidentification
,v_identificationqualifier
,v_typestatus
,v_identifiedby
,v_identifiedbyid
,v_dateidentified
,v_identificationreferences
,v_identificationverificationstatus
,v_identificationremarks
,v_taxonid
,v_scientificnameid
,v_acceptednameusageid
,v_parentnameusageid
,v_originalnameusageid
,v_nameaccordingtoid
,v_namepublishedinid
,v_taxonconceptid
,v_scientificname
,v_acceptednameusage
,v_parentnameusage
,v_originalnameusage
,v_nameaccordingto
,v_namepublishedin
,v_namepublishedinyear
,v_higherclassification
,v_kingdom
,v_phylum
,v_class
,v_order
,v_family
,v_subfamily
,v_genus
,v_genericname
,v_subgenus
,v_infragenericepithet
,v_specificepithet
,v_infraspecificepithet
,v_cultivarepithet
,v_taxonrank
,v_verbatimtaxonrank
,v_scientificnameauthorship
,v_vernacularname
,v_nomenclaturalcode
,v_taxonomicstatus
,v_nomenclaturalstatus
,v_taxonremarks
FROM $SOURCE_DB.$SOURCE_TABLE;"

/usr/local/gbif/trino.jar --insecure --debug --server "$TRINO_SERVER" --catalog=hive \
--schema="$DB" --session="hive.compression_codec=SNAPPY" --execute="$query" --user gbif --password
